number = 1
slug = "integrate-do-continue"
status = "completed"
description = "Add KDO and KCNT to snobol4/src/emit_asm.sno. KDO parses 'DO <lbl> <var> = <s..."
role = "production"
context_files = []
created_at = "2026-05-12T16:59:45"
completed_at = "2026-05-12T17:28:28"
commits = ["d73e2848ae7662b5fb95d6bac2a5ccce7e0ba166"]
